name: test-chart
description: Performs chart tests using https://github.com/silphid/testchart, if any present in `tests` sub-dir of chart.

inputs:

  work-dir:
    description: >
      Optional location where to perform operation. Defaults to workspace.
    required: false
    default: "."

  args:
    description: >
      Arguments to pass to test-chart command. Ex "--namespace my-namespace --release my-release --path /some/path/ --show-values"
    required: true

  version:
    description: >
      Version of testchart to use. Uses latest version if not specified. Ex: 0.0.27
    required: false
    
runs:
  using: 'composite'

  steps:
    - name: Determine latest version of testchart
      id: get-version
      shell: bash
      run: |
        if [ -z "${{ inputs.version }}" ]; then
          VERSION=$(curl -s https://api.github.com/repos/silphid/testchart/releases/latest | grep tag_name | cut -d '"' -f 4 | sed 's/^v//')
          echo "Latest version of testchart is v$VERSION"
          echo "version=$VERSION" >> $GITHUB_OUTPUT
        else
          echo "version=${{ inputs.version }}" >> $GITHUB_OUTPUT
        fi

    - name: Perform chart tests
      shell: bash
      run: |
        cd ${{ inputs.work-dir }}
        
        # Install testchart
        BIN_DIR=$HOME/bin
        mkdir -p $BIN_DIR
        VERSION=${{ steps.get-version.outputs.version }}
        curl -sLo $BIN_DIR/testchart.tar.gz https://github.com/silphid/testchart/releases/download/v$VERSION/testchart_${VERSION}_linux_amd64.tar.gz
        tar xvzf $BIN_DIR/testchart.tar.gz -C $BIN_DIR

        # Build testchart command
        command="$BIN_DIR/testchart run ${{ inputs.args }}"

        # Add ignore patterns passed as a multi-line string, if any
        while IFS= read -r line; do
          command+=" --ignore '$line'"
        done <<< "${{ inputs.ignore }}}"

        # Run testchart
        eval "$command"
