name: tag-commit
description: Adds given tag to git commit and pushes tag to remote.

inputs:

  work-dir:
    description: |
      Optional directory in which to perform operation. Defaults to workspace.
    required: false
    default: .

  commit:
    description: |-
      Optional commit to be tagged, defaulting to current branch's `HEAD`. Can be specified
      using any of the formats supported by `git tag`, such as:
        - Commit SHA (eg: `c4fe2b8f6a78d9f4d9f8184a20b68f8d6677d053`)
        - Short commit SHA (eg: `c4fe2b8`)
        - Branch reference (eg: `master`)
        - Tag reference (eg: `v0.0.1`)
        - etc.
    required: false
    default: ""

  tag:
    description: Value of tag to add to given commit.
    required: true

runs:
  using: 'composite'
  steps:

    - name: Add and push commit tag
      shell: bash
      run: |-
        cd ${{ inputs.work-dir }}

        git config user.name "GitHub Actions"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        git tag ${{ inputs.tag }} ${{ inputs.commit }} --message 'Tagged in: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
        git push origin ${{ inputs.tag }}
